### ISSUE TITLE
Progress and Todo

### ISSUE THREAD

**Issue by Tmplt** [Tmplt/fuzzywuzzy#1]
Implementation Progress
---
Simple and advanced scoring functions:

- [X] `ratio()`
- [x] `partial_ratio()`
  - [X] fix coredump
- [x] `token_sort_ratio()`
- [x] `partial_token_sort_ratio()`
- [x] `token_set_ratio()`
- [x] `partial_token_set_ratio()`

Combination API:

- [x] `QRatio()`
  - [x] port the code over
  - [x] test that it works
- [x] `WRatio()`
  - [x] port the code over
  - [x] fix segfault

Other:
- [ ] Process
  - [ ] `extractWithoutOrder()`
  - [ ] `extract()`
  - [ ] `extractBests()`
  - [ ] `extractOne()`
  - [ ] `dedupe()`
 - [ ] Unicode equivalent of the simple/advanced scoring functions

TODO
----
 - [x] Compile the C code with a C-compiler instead?
 - [x] Rename `diffutils` to `̶w̶r̶a̶p̶` `wrapper`?
 - [ ] Add compiler requirements to `README`.
- [ ] Copy test bench from the Python library.
- [ ] Generalize `fuzzywuzzy.hpp` with templates (objects exposing a `.c_str()`)?
 - [x] Split headers into an `include` directory.
- [ ] Use the [ICU library](http://site.icu-project.org/) for string operations?

**Comment by Tmplt** [comment]
The partial ratio between the strings "dragon" and "cock" is reported as 20 from the Python library. This implementation gives a 0, which is expected since no `LEV_EDIT_KEEP`s are generated from `get_opcodes()` (`LEV_EDIT_KEEP`s are required to find a matching block).

All other strings I've tried gives the correct result, and [this issue](https://github.com/seatgeek/fuzzywuzzy/issues/128) mentions that difflib can in some cases give different ratios from Levenshtein. I'll chalk this difference up as such a case.

**Comment by Tmplt** [comment]
I keep getting ratios that do not match the Python implementation. When porting the library over I omitted the `force_ascii` part. Could that be the cause?

**Comment by Tmplt** [comment]
Deprecating.
